/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:54f27a26-c0c4-4b11-8261-8d17fad65c93",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_fgF5EYLou",
    "aws_user_pools_web_client_id": "250l2v56tq4bhigqdtvf716gq",
    "oauth": {}
};


export default awsmobile;
